import "./main.css";

import * as THREE from "three";
import { ARButton } from "./jsm/webxr/ARButton.js";
import { NFTStorage } from "nft.storage";
import { OrbitControls } from "./jsm/controls/OrbitControls.js";
import { GLTFLoader } from "./jsm/loaders/GLTFLoader.js";
import { GLTFExporter } from "./jsm/exporters/GLTFExporter.js";
import { DRACOLoader } from "./jsm/loaders/DRACOLoader.js";
import { MeshoptDecoder } from "./jsm/libs/meshopt_decoder.module.js";
import { MeshSurfaceSampler } from "./jsm/math/MeshSurfaceSampler.js";
import {
  Brush,
  Evaluator,
  //ADDITION              // A ∪ B
  SUBTRACTION, // A - B 1
  REVERSE_SUBTRACTION, // B - A 2
  DIFFERENCE, // A ⊕ B 3
  INTERSECTION // A ∩ B
} from "three-bvh-csg";
//import html2canvas from "https://cdn.skypack.dev/html2canvas";

const params = {
  operation: 3,
  wireframe: false,
  displayBrushes: false,
  shadows: true,
  useGroups: true,

  randomize: () => {
    updateCSG();
  }
};

let geo;
const currentDate = new Date();

let node;
let renderer;
let camera;
let scene;
let outputContainer;
let pitcherBrush;
let brush;
let surfaceSampler;
let resultObject;
let result;
const csgEvaluator = new Evaluator();
let isAR = false;
let outputEl;
const gltfparams = {
  trs: false,
  onlyVisible: false,
  binary: true,
  maxTextureSize: 1024
};

async function getLocation(metadata) {
  const options = {
    enableHighAccuracy: true,
    timeout: 5000,
    maximumAge: 0
  };

  function success(pos) {
    const crd = pos.coords;

    metadata.attributes.push({
      trait_type: "Latitude",
      value: crd.latitude
    });
    metadata.attributes.push({
      trait_type: "Longitude",
      value: crd.longitude
    });
  }

  function error(err) {
    console.warn(`ERROR(${err.code}): ${err.message}`);
  }
  if (navigator.geolocation) {
    showMessage(`> getting your location`);
    geo = navigator.geolocation.getCurrentPosition(
      success,
      error,
      options
    );
  }
}

csgEvaluator.attributes = ["position", "normal"];
csgEvaluator.useGroups = true;

async function exportGLTF(input) {
  const gltfExporter = new GLTFExporter();

  const options = {
    trs: gltfparams.trs,
    onlyVisible: gltfparams.onlyVisible,
    binary: gltfparams.binary,
    maxTextureSize: gltfparams.maxTextureSize
  };
  gltfExporter.parse(
    input,
    function (resultE) {
      if (resultE instanceof ArrayBuffer) {
        saveArrayBuffer(resultE, "scene.glb");
      } else {
        const gltfText = JSON.stringify(resultE, null, 2);
        saveString(gltfText, "scene.gltf");
      }
    },
    function (error) {
      console.log("An error happened during parsing", error);
    },
    options
  );
}
const link = document.createElement("a");
link.style.display = "none";
document.body.appendChild(link); // Firefox workaround, see #6594

async function showMessage(text) {
  node = document.createElement("div");
  node.id = "node";
  node.innerText = text;
  const overlayOutput = document.getElementById("overlayOutput");

  if (isAR && overlayOutput) {
    overlayOutput.appendChild(node);
  } else if (outputEl) {
    outputEl.appendChild(node);
  }
}

async function showLink(url) {
  node = document.createElement("a");
  node.id = "node-l";
  node.href = url;
  node.innerText = `> ${url}`;
  node.target = "_blank";
  const overlayOutput = document.getElementById("overlayOutput");

  if (isAR && overlayOutput) {
    overlayOutput.appendChild(node);
  } else if (outputEl) {
    outputEl.appendChild(node);
  }
}

async function save(blob, filename) {
  const file = [new File([blob], filename)];
  showMessage("> creating NFT.storage client");
  const token =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweGJhODFBQkJGOEJkQ0ZkMTA0QTE2RUU3NjU2MjAzMzQzN0UyQzgzMGMiLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTY4MzkyMDM2OTYxOCwibmFtZSI6Ik1pbGttYWlkJ3MgUGl0Y2hlciJ9.yIQyeuFRGZKiTLoCIKUCwHBaV5L6tSV97M-jfHgms1k";

  const client = new NFTStorage({ token: token });
  const metadata = {
    name: "Milkmaid's Pitcher",
    description:
      "A unique 3d model generated by 'Milkmaid's Pitcher' digital art installation. The pitcher is part of the 'Dystopia of Imitation' collection.",
    image:
      "ipfs://bafkreiguof3bexge6u63rdl6slzgh7qbnglee67lhbgbu5sfids6oatayq",
    attributes: [
      {
        trait_type: "Artist",
        value: "Jarek Solecki @ Dystopia of imitation"
      },
      {
        trait_type: "Date",
        value: currentDate
      }
    ]
  };
  const options = {
    pin: true
  };

  await getLocation(metadata);

  const cid = await client.storeBlob(blob, metadata, options);

  showMessage(`> NFT.storage now hosting ${cid}`);
  showMessage("> you can download your own");
  showMessage(`> "Milkmaid's pitcher" from: `);
  showLink(`https://ipfs.io/ipfs/${cid}`);
  showMessage(`> some browsers refresh the page`);
  showMessage(`> after downloading the file`);
  //}
}

function saveString(text, filename) {
  save(new Blob([text], { type: "text/plain" }), filename);
}

function saveArrayBuffer(buffer, filename) {
  save(
    new Blob([buffer], { type: "application/octet-stream" }),
    filename
  );
}

async function downloadPitcher(event) {
  if (event && typeof event.preventDefault === "function") {
    event.preventDefault();
  }
  csgEvaluator.useGroups = params.useGroups;
  result = csgEvaluator.evaluate(
    pitcherBrush,
    brush,
    params.operation,
    result
  );

  result.castShadow = true;
  result.receiveShadow = true;

  /////////////////////////////////
  // Instantiate a exporter
  exportGLTF(result);
}

var saveFile = function (strData, filename) {
  var link = document.createElement("a");
  if (typeof link.download === "string") {
    document.body.appendChild(link); //Firefox requires the link to be in the body
    link.download = filename;
    link.href = strData;
    link.click();
    document.body.removeChild(link); //remove the link when done
  } else {
    location.replace(uri);
  }
};

function getScreenshot() {
  const canvas = document.querySelector("canvas");
  if (!canvas) {
    return;
  }
  canvas.toBlob((blob) => {
    if (blob) {
      saveBlob(blob, `screencapture-${canvas.width}x${canvas.height}.png`);
    }
  });
}
function getARScreenshot() {
  const canvas = renderer.domElement;
  if (!canvas) {
    return;
  }
  canvas.toBlob((blob) => {
    if (blob) {
      saveBlob(blob, `screencapture-${canvas.width}x${canvas.height}.png`);
    }
  });
}
const saveBlob = (function () {
  const a = document.createElement("a");
  document.body.appendChild(a);
  a.style.display = "none";
  return function saveData(blob, fileName) {
    const url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = fileName;
    a.click();
  };
})();

async function init() {
  outputEl = document.querySelector("#output");

  const infoSection = document.getElementById("high");
  const closeInfoButton = document.getElementById("myButton");
  const openInfoButton = document.getElementById("see-info");

  if (closeInfoButton && openInfoButton && infoSection) {
    closeInfoButton.addEventListener("click", () => {
      infoSection.style.display = "none";
      openInfoButton.style.display = "block";
    });

    openInfoButton.addEventListener("click", () => {
      infoSection.style.display = "block";
      openInfoButton.style.display = "none";
    });
  }

  const downloadButton = document.createElement("button");
  const textOnButton = document.createTextNode("get a 3D model");
  downloadButton.appendChild(textOnButton);
  document.body.appendChild(downloadButton);
  downloadButton.style.opacity = "0.5";
  downloadButton.addEventListener("pointerover", () => {
    downloadButton.style.opacity = "1";
  });
  downloadButton.addEventListener("pointerout", () => {
    downloadButton.style.opacity = "0.5";
  });
  downloadButton.addEventListener("pointerdown", downloadPitcher);
  downloadButton.id = "download-button";
  /////////////////////////////////

  showMessage("> you can take a 3D model of the object...");

  outputContainer = document.getElementById("loading");

  // renderer setup
  renderer = new THREE.WebGLRenderer({
    antialias: true,
    alpha: true,
    preserveDrawingBuffer: true
  });
  renderer.setPixelRatio(window.devicePixelRatio);
  renderer.setSize(window.innerWidth, window.innerHeight);
  //renderer.setClearColor(bgColor, 1);
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = THREE.PCFSoftShadowMap;
  if ("outputColorSpace" in renderer) {
    renderer.outputColorSpace = THREE.SRGBColorSpace;
  } else {
    renderer.outputEncoding = THREE.sRGBEncoding;
  }
  renderer.xr.enabled = true;
  renderer.domElement.id = "myCanvas";
  document.body.appendChild(renderer.domElement);

  isAR = renderer.xr.isPresenting;

  document.body.appendChild(ARButton.createButton(renderer));

  //////////////////////////////////
  const screenShotButton = document.getElementById("screenshot");
  if (screenShotButton) {
    screenShotButton.style.zIndex = "1000000";
    //screenShotButton.addEventListener("click", getScreenshot);
    screenShotButton.addEventListener("pointerdown", getScreenshot);
  }

  /////////////////////////////////

  // scene setup
  scene = new THREE.Scene();
  const texture = new THREE.TextureLoader().load(
    "/textures/landscape.jpg",
    render
  );
  texture.mapping = THREE.EquirectangularReflectionMapping;
  scene.background = texture;

  // lights

  const light1 = new THREE.DirectionalLight(0xffffff, 4);
  light1.position.set(0, 2, 3);
  scene.add(light1, new THREE.AmbientLight(0xb0bec5, 1));

  // camera setup
  camera = new THREE.PerspectiveCamera(
    70,
    window.innerWidth / window.innerHeight,
    0.01,
    20
  );

  const controls = new OrbitControls(camera, renderer.domElement);
  controls.autoRotate = true;
  controls.target.set(0, 0, -1);
  controls.update();

  const dracoLoader = new DRACOLoader();
  dracoLoader.setDecoderPath("/draco/");
  const gltf = await new GLTFLoader()
    .setDRACOLoader(dracoLoader)
    .setMeshoptDecoder(MeshoptDecoder)
    .loadAsync("/models/Pitcjer2100.glb");
  const geometry = gltf.scene.children[0].geometry;

  geometry.computeVertexNormals();
  if (geometry) {
    outputContainer.style.display = "none";
  }

  pitcherBrush = new Brush(geometry, new THREE.MeshStandardMaterial());
  pitcherBrush.position.y = -0.5;
  pitcherBrush.updateMatrixWorld();
  pitcherBrush.receiveShadow = true;
  pitcherBrush.rotation.x = 120 * (Math.PI / 180);
  pitcherBrush.rotation.y = 20 * (Math.PI / 180);
  pitcherBrush.rotation.z = 190 * (Math.PI / 180);

  pitcherBrush.position.set(0.5, -0.5, -3);
  pitcherBrush.scale.set(0.5, 0.5, 0.5);

  surfaceSampler = new MeshSurfaceSampler(pitcherBrush);
  surfaceSampler.build();

  pitcherBrush.material.depthFunc = THREE.AlwaysDepth;
  pitcherBrush.material.depthWrite = true;
  pitcherBrush.material.polygonOffset = true;
  pitcherBrush.material.polygonOffsetFactor = 0.1;
  pitcherBrush.material.polygonOffsetUnits = 0.1;
  pitcherBrush.material.side = THREE.DoubleSide;
  pitcherBrush.material.color.set(0xff8659);
  // add object displaying the result
  resultObject = new THREE.Mesh(
    new THREE.BufferGeometry(),
    new THREE.MeshStandardMaterial({
      roughness: 0.1,
      flatShading: true,
      polygonOffset: true,
      polygonOffsetUnits: 1,
      polygonOffsetFactor: 1
    })
  );
  resultObject.material.transparent = false;
  resultObject.castShadow = true;
  resultObject.receiveShadow = true;
  scene.add(resultObject);

  dracoLoader.setDecoderPath("/draco/");
  const gltfbrush = await new GLTFLoader()
    .setDRACOLoader(dracoLoader)
    .setMeshoptDecoder(MeshoptDecoder)
    .loadAsync("/models/fluid1300tr.glb");

  const geometrybrush = gltfbrush.scene.children[0].geometry;
  geometrybrush.computeVertexNormals();

  brush = new Brush(
    geometrybrush,
    new THREE.MeshStandardMaterial({
      color: 0x00cbff, //0x80cbc4,
      opacity: 0.5,
      polygonOffset: true,
      polygonOffsetUnits: 1,
      polygonOffsetFactor: 1
    })
  );
  brush.scale.set(0.02, 0.09, 0.05);
  brush.position.set(0.2, 0, -2.5);
  brush.rotation.x = (90 * Math.PI) / 180;
  brush.updateMatrixWorld();

  renderer.xr.addEventListener("sessionstart", function () {
    if (outputEl) {
      outputEl.style.display = "none";
    }

    const arButtonElement = document.getElementById("ARButton");
    const overlayRoot = document.getElementById("aroverlay");
    if (arButtonElement && overlayRoot) {
      overlayRoot.appendChild(arButtonElement);
    }
    /*
    const overlayOutput = document.createElement("div");
    overlayOutput.id = "overlayOutput";
    overlayOutput.style = "bottom: 4em";
*/
    node = document.createElement("div");
    node.id = "node";
    //node.style = "bottom: 2em";
    node.innerText =
      "> take a 3D static snapshot of this unique scuplpture";
    const overlayOutput = document.getElementById("overlayOutput");
    if (overlayOutput) {
      overlayOutput.appendChild(node);
    }

    showMessage("> take a 3D snapshot of this unique scuplpture");
    ////
    const ARdownloadButton = document.getElementById("ARdownloadButton");

    if (ARdownloadButton) {
      ARdownloadButton.addEventListener("pointerdown", downloadPitcher);
    }

    scene.background = null;
    if (params.operation === 3) {
      params.operation = 1;
    }
    isAR = renderer.xr.isPresenting;

    updateCSG();
  });
  window.addEventListener(
    "resize",
    function () {
      camera.aspect = window.innerWidth / window.innerHeight;
      camera.updateProjectionMatrix();

      renderer.setSize(window.innerWidth, window.innerHeight);
    },
    false
  );
}

async function updateCSG() {
  if (pitcherBrush && brush) {
    csgEvaluator.useGroups = params.useGroups;
    result = csgEvaluator.evaluate(
      pitcherBrush,
      brush,
      params.operation,
      result
    );

    result.castShadow = true;
    result.receiveShadow = true;
    scene.add(result);
  }
}
////////////////////////////////////////////////////////////////////////////////////

const rotatePitcher = () => {
  if (pitcherBrush) {
    const t = window.performance.now() + 9000;
    pitcherBrush.rotation.z = t * -0.0002;
    //pitcherBrush.rotation.x = t * 0.0001;
    //pitcherBrush.rotation.y = t * 0.0001;
    pitcherBrush.updateMatrixWorld();
  }
  if (brush) {
    const t = window.performance.now() + 9000;
    brush.rotation.y = t * -0.0005;
    brush.rotation.x = t * -0.0000005;
    brush.rotation.z = t * -0.00005;
    brush.updateMatrixWorld();
  }
};

function animate() {
  renderer.setAnimationLoop(render);
}

function render() {
  rotatePitcher();
  updateCSG();

  renderer.render(scene, camera);
}

async function start() {
  try {
    await init();
    animate();
  } catch (error) {
    console.error("Failed to initialise scene", error);
  }
}

if (document.readyState === "loading") {
  window.addEventListener("DOMContentLoaded", start);
} else {
  start();
}
